baseURL = "/"
languageCode = "en-us"
title = "Fluentd | Open Source Data Collector | Unified Logging Layer"

googleAnalytics = "" 

[params]
email = ""
logo = "/images/miscellaneous/fluentd-logo.png"
logo2 = "/images/logo-white.svg"
footer_logo = "/images/footer-logo.svg"
copyright = "Â© 2010-2022 The Fluentd Project. Fluentd is a CNCF graduated project."
lastVersion = "v1.15.2"
releasedOn = "August 22, 2022"
noteUrl = "https://docs.fluentd.org/"

   [menu]
    [[menu.main]]
        identifier = "documentation"
        url = "https://docs.fluentd.org/"
        name = "DOCUMENTATION"
        weight = 1
        tab = "external" 
    [[menu.main]]
        identifier = "how it works"
        url = "/how-it-works/"
        name = "how it works"
        weight = 2
    [[menu.main]]
        identifier = "release notes"
        url = "/announcements/"
        name = "RELEASE NOTES"
        weight = 3    
    [[menu.main]]
        identifier = "Enterprise"
        url = "/enterprise/"
        name = "Enterprise"
        weight = 4    
    [[menu.main]]
        identifier = "Community"
        url = "/community/"
        name = "Community"
        weight = 5 
    [[menu.main]]
        identifier = "blog"
        url = "/blog/"
        name = "Blog"
        weight = 7   

    [[menu.main]]
        identifier = "slack"
        url = "https://launchpass.com/fluent-all"
        name = "slack"
        weight = 8
        pre = "/other-images/slack.svg"
        slack = "/other-images/slack-w.svg"
    # [[menu.main]]
    #     identifier = "downloadNow"
    #     url = "https://launchpass.com/fluent-all"
    #     name = "download now"
    #     weight = 9
    #     pre = "/images/DN-Button.png"
    #     slack = "/images/DN-Button.png"

    
    [params.latestVer]
    light = "true"
    text = "Check out the Release Notes, read the Updated Documentation or jump directly to the Downloads Section."
    smallText = "We are part of a wide community, <strong>no vendor lock-in.</strong>"
    btnText = "Download Now"
    btnUrl = "https://docs.fluentd.org/installation/before-install"
    bottomText = ":: Read Documentation"
    bottomUrl = "https://docs.fluentd.org/installation/before-install"

    
    [[params.footer.bottom]]
        url = "#"
        name = "Terms & Conditions"
        weight = 1
    [[params.footer.bottom]]
        url = "#"
        name = "Privacy Policy"
        weight = 2
    [[params.footer.bottom]]
        url = "#"
        name = "Sitemap"
        weight = 3
    [[params.footer.bottom]]
        url = "#"
        name = "Disclaimer"
        weight = 4

 [[params.social]]
    url   = "https://launchpass.com/fluent-all"
    icon  = "/images/slack-color.svg" 
    name = "slack"
 [[params.social]]
    url   = "https://twitter.com/fluentd"
    icon  = "/images/twitter-color.svg" 
    name = "twitter"




[permalinks]
    posts = "blog/:year/:month/:day/:title/"
    pages = ":slug/"





[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]


  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = true
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
    extensions = ["hardLineBreak"]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = '2 3'
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'api' 
    tabWidth = 20
    # style= 'monika api fruity monokai native paraiso-dark rrt solarized-dark solarized-dark256 swapoff vim'

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  
  [markup.goldmark.renderer]
    unsafe= true

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10
